const getElement = (id) => document.getElementById(id)

export const termsModal               = getElement('termsModal')
export const acceptTermsBtn           = getElement('acceptTermsBtn')
export const changelogModal           = getElement('changelogModal')
export const changelogBtn             = getElement('changelogBtn')
export const changelogContent         = getElement('changelogContent')
export const closeChangelogBtn        = getElement('closeChangelogBtn')
export const userHandleInput          = getElement('userHandleInput')
export const userAvatarBadge          = getElement('userAvatarBadge')
export const toggleAudioBtn           = getElement('toggleAudioBtn')
export const channelNameInput         = getElement('channelNameInput')
export const publicDiscoveryToggle    = getElement('publicDiscoveryToggle')
export const connectChannelBtn        = getElement('connectChannelBtn')
export const refreshDiscoveryBtn      = getElement('refreshDiscoveryBtn')
export const searchChannelsInput      = getElement('searchChannelsInput')
export const discoveredRoomsContainer = getElement('discoveredRoomsContainer')

export const currentRoomHeader   = getElement('currentRoomHeader')
export const messageCounterBadge = getElement('messageCounterBadge')
export const messageCounterText  = getElement('messageCounterText')
export const copyRoomLinkBtn     = getElement('copyRoomLinkBtn')
export const toggleMembersBtn    = getElement('toggleMembersBtn')
export const leaveRoomBtn        = getElement('leaveRoomBtn')

export const messageStreamFeed     = getElement('messageStreamFeed')
export const emptyStatePlaceholder = getElement('emptyStatePlaceholder')
export const chatMessageInput      = getElement('chatMessageInput')
export const fileAttachmentInput   = getElement('fileAttachmentInput')
export const attachFileBtn         = getElement('attachFileBtn')
export const sendMessageBtn        = getElement('sendMessageBtn')
export const stagedFilesContainer  = getElement('stagedFilesContainer')

export const membersSidebar    = getElement('membersSidebar')
export const activeMembersList = getElement('activeMembersList')
export const memberCountBadge  = getElement('memberCountBadge')

export const versionLabel = document.querySelector('.sidebar-brand .brand-version')